# -*- coding: utf-8 -*-
"""Laiba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxpsMGSaHEat8P1EfUs1ucHvqjfd9Ivq
"""

pip install Biopython

"""**Fetched Genome sequence and calculates the length, molecular weight, GC content, and nucleotide composition, translation of the genome**"""

from Bio import Entrez, SeqIO
Entrez.email = "laibamaqsood786@gmail.com"
handle = Entrez.efetch(db="nucleotide", id="MN908947", rettype="gb", retmode="text")
recs = list(SeqIO.parse(handle, 'gb'))
handle.close()
print(recs)
CO_dna = recs[0].seq
print(CO_dna)
print(f'The genome of Covid-19  consists of {len(CO_dna)} nucleotides.')
from Bio.SeqUtils import molecular_weight
mw=molecular_weight(CO_dna)
print(mw)
from Bio.SeqUtils import gc_fraction
gf=gc_fraction(CO_dna)
print(gf)
count_nucleotides = {
    'A': CO_dna.count('A'),
    'T': CO_dna.count('T'),
    'C': CO_dna.count('C'),
    'G': CO_dna.count('G')
}
print(count_nucleotides)
CO_mrna = CO_dna.transcribe()
print(CO_mrna)
CO_aa = CO_mrna.translate()
print(CO_aa)
from collections import Counter
common_amino = Counter(CO_aa)
print(common_amino.most_common(10))
del common_amino['*']
print(f"Covid-19 genome has {sum(common_amino.values())} amino acids")
proteins = CO_aa.split('*')
proteins[:5]
print(f'We have {len(proteins)} amino acids in the Covid-19 genome')
for protein in proteins:
    if len(protein) < 20:
        proteins.remove(protein)
print(f'We have {len(proteins)} proteins with more than 20 amino acids in the Covid-19 genome')
top_5_proteins = sorted(proteins, key = len)
top_5_proteins[-1]
len(top_5_proteins[-1])

import matplotlib.pyplot as plt
width = 0.5
plt.bar(count_nucleotides.keys(), count_nucleotides.values(), width, color=['b', 'r', 'm', 'c'])
plt.xlabel('Nucleotide')
plt.ylabel('Frequency')
plt.title('Nucleotide Frequency')
plt.show()

width = 0.5
plt.bar(common_amino.keys(), common_amino.values(), width, color=['b', 'r', 'm', 'c'])
plt.xlabel('Amino Acid')
plt.ylabel('Frequency')
plt.title('Protein Sequence Frequency')
plt.show()

"""**Translation**"""

from Bio.Seq import Seq
from Bio import SeqIO
coding_dna=Seq('ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG')
messenger_rna = coding_dna.transcribe()
print(messenger_rna)
#infleunza
coding_dna2=Seq('ATGGATTCAAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTTGGCATGTCCGCAAACTGTTTGCGGACTGGGGGAGTGGCGATGCCCCATTTCTCGATAGGCTTCGCCGAGACCAGAAATCCCTAAGAGGGAGAGGCAACACTCTTGGCCTGGAAATCGAACCAGCTACTCGTGCGGGAAAACAAATAGTGAAGCGTATTCTGGAAGAAGAATACGAGGAGGCACTTAAAATAACTATCGCTTCTGTGCCTGCTTCACGCTATCTAACTGACATGACTCTTGAAGAGATGTCAAGAGACTGGTTCATGCTCATGCCCAAGCAGAAAGTGGCAGGTTCCCTTTGCATCAAAATGGACCAAGCAATAATGGATAAAAACATCACATTGAAAGCAAACTTCAGTGTGGTTTTTAACCGACTGGAAACTCTAATACTCCTTAGAGCTTTCACAGAAGAAGGGGCAATTGTAGGTGAAATCTCACCGGTACCTTCTCTTCCAGGACATACTAACGAGGATGTCAAAAATGCAATTGGGATCCTCATCAAAGGACTTGAGTG')
messenger_rna2 = coding_dna2.transcribe()
print(messenger_rna2)
#typhoid
coding_dna3=Seq('GCCAGATGTACGCGATCGCGTGCGGTAAGGCGAATAAAGGTACTATAGACCATATGAATATCCTCCTTAG')
messenger_rna3 = coding_dna3.transcribe()
print(messenger_rna3)
#heart
coding_dna4=Seq('TTATGTGCAGACAACATTGAAGGAARGACATTTGTTTCAACAGTAAATTCT')
messenger_rna4 = coding_dna4.transcribe()
print(messenger_rna4)
#brain cancer
coding_dna5=Seq('CTACCTGATGGAACGGCACGAGGTT')
messenger_rna5 = coding_dna5.transcribe()
print(messenger_rna5)